spring.datasource.url=jdbc:mysql://localhost:3306/inventory_db
spring.datasource.username=root
spring.datasource.password=Bishwanath@234
spring.jpa.hibernate.ddl-auto=update

# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/inventory_db
#     username: root
#     password: your_password
#   jpa:
#     hibernate:
#       ddl-auto: update
